# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/FPGA_EGR680/counter/counter.srcs/sources_1/bd/counter/ip/counter_c_counter_binary_0_0/counter_c_counter_binary_0_0.xci
# IP: The module: 'counter_c_counter_binary_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/FPGA_EGR680/counter/counter.srcs/sources_1/bd/counter/ip/counter_c_counter_binary_0_0/counter_c_counter_binary_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'counter_c_counter_binary_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: c:/FPGA_EGR680/counter/counter.srcs/sources_1/bd/counter/ip/counter_c_counter_binary_0_0/counter_c_counter_binary_0_0.xci
# IP: The module: 'counter_c_counter_binary_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/FPGA_EGR680/counter/counter.srcs/sources_1/bd/counter/ip/counter_c_counter_binary_0_0/counter_c_counter_binary_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'counter_c_counter_binary_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
