# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/FPGA_EGR680/counter/counter.cache/wt [current_project]
set_property parent.project_path C:/FPGA_EGR680/counter/counter.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/FPGA_EGR680/counter/counter.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib C:/FPGA_EGR680/counter/counter.srcs/sources_1/bd/counter/hdl/counter_wrapper.v
add_files C:/FPGA_EGR680/counter/counter.srcs/sources_1/bd/counter/counter.bd
set_property used_in_implementation false [get_files -all c:/FPGA_EGR680/counter/counter.srcs/sources_1/bd/counter/ip/counter_c_counter_binary_0_0/counter_c_counter_binary_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/FPGA_EGR680/counter/counter.srcs/sources_1/bd/counter/counter_ooc.xdc]
set_property is_locked true [get_files C:/FPGA_EGR680/counter/counter.srcs/sources_1/bd/counter/counter.bd]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top counter_wrapper -part xc7z020clg400-1


write_checkpoint -force -noxdef counter_wrapper.dcp

catch { report_utilization -file counter_wrapper_utilization_synth.rpt -pb counter_wrapper_utilization_synth.pb }
