# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/counter/counter.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==counter || ORIG_REF_NAME==counter}]

# IP: bd/counter/ip/counter_c_counter_binary_0_0/counter_c_counter_binary_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==counter_c_counter_binary_0_0 || ORIG_REF_NAME==counter_c_counter_binary_0_0}]

# XDC: bd/counter/counter_ooc.xdc
